import { priceYes, priceNo } from './math.js';
import type { AppState, Claim, PricePoint } from './types.js';

const INITIAL_BALANCE = 1;

function generateId(): string {
  return crypto.randomUUID();
}

export interface DemoClaimsData {
  claims: Claim[];
  priceHistory: Record<string, PricePoint[]>;
}

export function createDemoClaimsData(): DemoClaimsData {
  const now = Date.now();

  const claims: Claim[] = [
    {
      id: generateId(),
      title: 'Artificial general intelligence will be achieved before 2030',
      description: 'An AI system will demonstrate general problem-solving ability across all major human cognitive domains before January 1, 2030.',
      creatorId: 'demo',
      createdAt: now - 86400000 * 10,
      yesStake: 2.1,
      noStake: 1.4,
    },
    {
      id: generateId(),
      title: 'More than 50% of software will be AI-generated by 2027',
      description: 'Over half of production code shipped globally will be primarily generated by AI systems by end of 2027.',
      creatorId: 'demo',
      createdAt: now - 86400000 * 7,
      yesStake: 1.8,
      noStake: 2.5,
    },
    {
      id: generateId(),
      title: 'The cost function C(y,n) = log₂(2ʸ + 2ⁿ) − 1 is a valid LMSR variant',
      description: 'This cost function has the required properties: convexity, bounded subsidy, and proper scoring.',
      creatorId: 'demo',
      createdAt: now - 86400000 * 3,
      yesStake: 3.0,
      noStake: 0.5,
    },
  ];

  const priceHistory: Record<string, PricePoint[]> = {};
  for (const claim of claims) {
    const points: PricePoint[] = [];
    const steps = 12;
    for (let i = 0; i <= steps; i++) {
      const t = i / steps;
      const y = claim.yesStake * t;
      const n = claim.noStake * t;
      points.push({
        timestamp: claim.createdAt + (now - claim.createdAt) * t,
        yesPrice: priceYes(y, n),
        noPrice: priceNo(y, n),
      });
    }
    priceHistory[claim.id] = points;
  }

  return { claims, priceHistory };
}

export function createInitialState(name: string): AppState {
  const userId = generateId();
  const { claims, priceHistory } = createDemoClaimsData();

  return {
    user: {
      id: userId,
      name,
      balance: INITIAL_BALANCE,
    },
    claims,
    transactions: [],
    positions: [],
    priceHistory,
  };
}