import type { AppState, AppAction, Claim, Position, PricePoint, Transaction, TradeType } from './types';
import { priceYes, priceNo, costToBuyYes, costToBuyNo } from './math';

const INITIAL_BALANCE = 1;

function generateId(): string {
  return Math.random().toString(36).slice(2) + Date.now().toString(36);
}

function getOrCreatePosition(positions: Position[], claimId: string): Position {
  const existing = positions.find(p => p.claimId === claimId);
  if (existing) return existing;
  return { claimId, yesShares: 0, noShares: 0 };
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

export function createInitialState(name: string): AppState {
  const userId = generateId();
  const now = Date.now();

  // Seed some demo claims
  const demoClaims: Claim[] = [
    {
      id: generateId(),
      title: 'Artificial general intelligence will be achieved before 2030',
      description: 'An AI system will demonstrate general problem-solving ability across all major human cognitive domains before January 1, 2030.',
      creatorId: 'demo',
      createdAt: now - 86400000 * 10,
      yesStake: 2.1,
      noStake: 1.4,
    },
    {
      id: generateId(),
      title: 'More than 50% of software will be AI-generated by 2027',
      description: 'Over half of production code shipped globally will be primarily generated by AI systems by end of 2027.',
      creatorId: 'demo',
      createdAt: now - 86400000 * 7,
      yesStake: 1.8,
      noStake: 2.5,
    },
    {
      id: generateId(),
      title: 'The cost function C(y,n) = log₂(2ʸ + 2ⁿ) − 1 is a valid LMSR variant',
      description: 'This cost function has the required properties: convexity, bounded subsidy, and proper scoring.',
      creatorId: 'demo',
      createdAt: now - 86400000 * 3,
      yesStake: 3.0,
      noStake: 0.5,
    },
  ];

  // Generate price history for demo claims
  const priceHistory: Record<string, PricePoint[]> = {};
  for (const claim of demoClaims) {
    const points: PricePoint[] = [];
    // Simulate price evolution from (0,0) toward current stakes
    const steps = 12;
    for (let i = 0; i <= steps; i++) {
      const t = i / steps;
      const y = claim.yesStake * t;
      const n = claim.noStake * t;
      points.push({
        timestamp: claim.createdAt + (now - claim.createdAt) * t,
        yesPrice: priceYes(y, n),
        noPrice: priceNo(y, n),
      });
    }
    priceHistory[claim.id] = points;
  }

  return {
    user: {
      id: userId,
      name,
      balance: INITIAL_BALANCE,
    },
    claims: demoClaims,
    transactions: [],
    positions: [],
    priceHistory,
  };
}

export function reducer(state: AppState, action: AppAction): AppState {
  switch (action.type) {
    case 'LOAD_STATE':
      return action.state;

    case 'SET_USERNAME': {
      return {
        ...state,
        user: { ...state.user, name: action.name },
      };
    }

    case 'CREATE_CLAIM': {
      const { id, title, description } = action;
      if (!title.trim()) return state;

      const newClaim: Claim = {
        id,
        title: title.trim(),
        description: description.trim(),
        creatorId: state.user.id,
        createdAt: Date.now(),
        yesStake: 0,
        noStake: 0,
      };

      const tx: Transaction = {
        id: generateId(),
        userId: state.user.id,
        claimId: newClaim.id,
        type: 'CREATE_CLAIM',
        shares: 0,
        cost: 0,
        timestamp: Date.now(),
        yesStakeAfter: 0,
        noStakeAfter: 0,
        balanceAfter: state.user.balance,
      };

      const initialPricePoint: PricePoint = {
        timestamp: newClaim.createdAt,
        yesPrice: 0.5,
        noPrice: 0.5,
      };

      return {
        ...state,
        claims: [...state.claims, newClaim],
        transactions: [...state.transactions, tx],
        priceHistory: {
          ...state.priceHistory,
          [newClaim.id]: [initialPricePoint],
        },
      };
    }

    case 'TRADE': {
      const { claimId, tradeType, shares } = action;
      if (shares <= 0) return state;

      const claim = state.claims.find(c => c.id === claimId);
      if (!claim) return state;

      const position = getOrCreatePosition(state.positions, claimId);
      const { yesStake: y, noStake: n } = claim;

      let tradeCost: number;
      let newY = y;
      let newN = n;
      let newYesShares = position.yesShares;
      let newNoShares = position.noShares;

      switch (tradeType) {
        case 'BUY_YES': {
          tradeCost = costToBuyYes(y, n, shares);
          if (tradeCost > state.user.balance + 1e-12) return state; // insufficient funds
          tradeCost = clamp(tradeCost, 0, state.user.balance);
          newY = y + shares;
          newYesShares = position.yesShares + shares;
          break;
        }
        case 'BUY_NO': {
          tradeCost = costToBuyNo(y, n, shares);
          if (tradeCost > state.user.balance + 1e-12) return state;
          tradeCost = clamp(tradeCost, 0, state.user.balance);
          newN = n + shares;
          newNoShares = position.noShares + shares;
          break;
        }
        case 'SELL_YES': {
          const maxSell = position.yesShares;
          const actualShares = Math.min(shares, maxSell);
          if (actualShares <= 0) return state;
          // Selling: receive the cost difference (positive receipt)
          tradeCost = costToBuyYes(y, n, -actualShares); // negative cost = receive
          newY = Math.max(0, y - actualShares);
          newYesShares = Math.max(0, position.yesShares - actualShares);
          // Use actualShares for the transaction record
          return applyTrade(state, claimId, tradeType, actualShares, tradeCost, newY, newN, newYesShares, position.noShares);
        }
        case 'SELL_NO': {
          const maxSell = position.noShares;
          const actualShares = Math.min(shares, maxSell);
          if (actualShares <= 0) return state;
          tradeCost = costToBuyNo(y, n, -actualShares);
          newN = Math.max(0, n - actualShares);
          newNoShares = Math.max(0, position.noShares - actualShares);
          return applyTrade(state, claimId, tradeType, actualShares, tradeCost, newY, newN, position.yesShares, newNoShares);
        }
        default:
          return state;
      }

      return applyTrade(state, claimId, tradeType, shares, tradeCost, newY, newN, newYesShares, newNoShares);
    }

    default:
      return state;
  }
}

function applyTrade(
  state: AppState,
  claimId: string,
  tradeType: TradeType,
  shares: number,
  tradeCost: number,
  newY: number,
  newN: number,
  newYesShares: number,
  newNoShares: number,
): AppState {
  const newBalance = state.user.balance - tradeCost;
  const timestamp = Date.now();

  const tx: Transaction = {
    id: generateId(),
    userId: state.user.id,
    claimId,
    type: tradeType,
    shares,
    cost: tradeCost,
    timestamp,
    yesStakeAfter: newY,
    noStakeAfter: newN,
    balanceAfter: newBalance,
  };

  const updatedClaims = state.claims.map(c =>
    c.id === claimId ? { ...c, yesStake: newY, noStake: newN } : c
  );

  const existingPositions = state.positions.filter(p => p.claimId !== claimId);
  const newPosition: Position = { claimId, yesShares: newYesShares, noShares: newNoShares };
  const updatedPositions = [...existingPositions, newPosition];

  const pricePoint: PricePoint = {
    timestamp,
    yesPrice: priceYes(newY, newN),
    noPrice: priceNo(newY, newN),
  };
  const existingHistory = state.priceHistory[claimId] ?? [];
  const updatedHistory = {
    ...state.priceHistory,
    [claimId]: [...existingHistory, pricePoint],
  };

  return {
    ...state,
    user: { ...state.user, balance: newBalance },
    claims: updatedClaims,
    transactions: [...state.transactions, tx],
    positions: updatedPositions,
    priceHistory: updatedHistory,
  };
}

const STORAGE_KEY = 'ppes_state';

export function loadFromStorage(): AppState | null {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as AppState;
  } catch {
    return null;
  }
}

export function saveToStorage(state: AppState): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // storage full or unavailable
  }
}

export function clearStorage(): void {
  localStorage.removeItem(STORAGE_KEY);
}
